# Generated by Django 3.1.2 on 2020-10-28 02:24

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_recipe_subtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="slug",
            field=models.SlugField(default="", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount_uom",
            field=models.CharField(
                choices=[
                    ("pinch", "pinch"),
                    ("dash", "dash"),
                    ("tsp", "tsp"),
                    ("tbsp", "tbsp"),
                    ("cup", "cup"),
                    ("pint", "pint"),
                    ("quart", "quart"),
                    ("gallon", "gallon"),
                    ("fluid-ounce", "fl-oz"),
                    ("weight-ounce", "ounce"),
                    ("pound", "pound"),
                    ("ml", "ml"),
                    ("liter", "liter"),
                    ("gram", "gram"),
                    ("kilogram", "kilogram"),
                    ("fuckton", "fuckton"),
                ],
                default="fuckton",
                help_text="Unit of measure for 'amount'.",
                max_length=20,
            ),
        ),
        migrations.AlterModelOptions(
            name="recipedirection",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="recipeingredient",
            options={"ordering": ["order", "pk"], "verbose_name": "Ingredient"},
        ),
        migrations.AlterField(
            model_name="recipedirection",
            name="order",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Order in which this direction appears in the list of directions for a recipe.",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="directions",
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.DeleteModel(
            name="RecipeDirection",
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="order",
            field=models.PositiveIntegerField(
                default=1,
                help_text=(
                    "Order in which this ingredient appears in the list of ingredients for a recipe. "
                    "If ordering doesn't matter, just leave this alone; but know that this list will "
                    "sort based on this field"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount_uom",
            field=models.CharField(
                choices=[
                    ("pinch", "pinch"),
                    ("dash", "dash"),
                    ("tsp", "teaspoon"),
                    ("tbsp", "tablespoon"),
                    ("cup", "cup"),
                    ("pint", "pint"),
                    ("quart", "quart"),
                    ("gallon", "gallon"),
                    ("fluid-ounce", "fluid ounce"),
                    ("weight-ounce", "ounce"),
                    ("pound", "pound"),
                    ("ml", "ml"),
                    ("liter", "liter"),
                    ("gram", "gram"),
                    ("kilogram", "kilogram"),
                    ("fuckton", "fuckton"),
                ],
                default="fuckton",
                help_text="Unit of measure for 'amount'.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="footnotes",
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount_uom",
            field=models.CharField(
                choices=[
                    ("pinch", "pinch"),
                    ("dash", "dash"),
                    ("tsp", "teaspoon"),
                    ("tbsp", "tablespoon"),
                    ("cup", "cup"),
                    ("pint", "pint"),
                    ("quart", "quart"),
                    ("gallon", "gallon"),
                    ("fluid-ounce", "fluid ounce"),
                    ("weight-ounce", "ounce"),
                    ("pound", "pound"),
                    ("ml", "ml"),
                    ("liter", "liter"),
                    ("gram", "gram"),
                    ("kilogram", "kilogram"),
                    ("fuckton", "fuckton"),
                    ("blank", "(blank)"),
                ],
                default="fuckton",
                help_text="Unit of measure for 'amount'.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="preparation",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
