# Generated by Django 3.1.2 on 2020-10-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_auto_20201029_1218"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Order in which this ingredient appears in the list of ingredients for a recipe. If ordering doesn't matter, just leave this alone; but know that this list will sort based on this field",
            ),
        ),
    ]
