# Generated by Django 3.1.2 on 2020-10-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_auto_20201029_1218"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
