# Generated by Django 3.1.2 on 2020-11-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0010_ingredienttype_plural_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="nutrition_label",
            field=models.ImageField(
                blank=True,
                default="",
                upload_to="nutrition_labels/",
            ),
        ),
    ]
