# Generated by Django 3.1.7 on 2021-03-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0014_auto_20201224_2033"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="is_private",
            field=models.BooleanField(
                default=True,
                help_text="If True (default), this recipe can only be viewed by logged-in members of this site. If False, unauthenticated guests can view this recipe, as well.",
                verbose_name="members only",
            ),
        ),
    ]
