title: Rice-Prower Recipes
description: >- # this means to ignore newlines until "baseurl:"
  We make good things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://recipes.riceprower.com/" # the base hostname & protocol for your site, e.g. http://example.com

# Some contact info
email: griceturrble@protonmail.com
github:
  username: griceturrble
  repo: recipes.riceprower.com

# https://jekyllrb.com/docs/collections/
collections:
  recipes:
    output: true
    permalink: /r/:name
    layout: "recipe"

defaults:
  - scope:
      path: ""
      type: "recipes"
    values:
      layout: "recipe"
      image:
        href: "https://place-hold.it/1200x800&text=Pineapple_Pizza&fontsize=36"
        alt_text: "image of some food (this has not been replaced for this recipe!)"

# Exclude certain files and directories from the build
# https://jekyllrb.com/docs/configuration/options/#global-configuration
exclude:
  - _algolia_api_key
  - .github
  - .vscode
  - '*.gem'
  - '*.gemspec'
  - docs
  - Gemfile
  - gulpfile.js
  - js_tools
  - LICENSE
  - Makefile
  - node_modules
  - package*.json
  - README.md

plugins:
  - jekyll-redirect-from

tooling:
  fontawesome_kit_url: https://kit.fontawesome.com/4f678b0cb8.js
  google_font_kit: https://fonts.googleapis.com/css2?family=Modern+Antiqua&family=Work+Sans:ital,wght@0,400;0,500;0,600;0,700;0,800;0,900;1,400;1,500;1,600;1,700;1,800;1,900&display=swap
  algolia_instant_search: https://cdn.jsdelivr.net/npm/instantsearch.js@2.10.4

algolia:
  application_id: "TM5MJ9QNSU"
  search_api_key: "75093c3e6d1abf1e90085b0e99d8d2cd"
  # This API key is safe to be public facing, as it has read-only access to Algolia.
  index_name: "prod_recipes_riceprower_com"
  files_to_exclude:
    - recipe_list.html
    - index.html
    - index.md
  settings:
    hitsPerPage: 5
    searchableAttributes:
      - title
      - subtitle
      - ingredients,directions,footnotes
      - content
