version: "3"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJ_DEBUG=True
      - DJ_SECRET_KEY=Tot4llyInsecur3SecretKey-DO-NOT-USE-IN-PRODUCTION
      - DJ_DB_URL=postgresql://django_app_user:django_app_password@database:5432/django_app_db
    volumes:
      - ./recipesite:/home/appuser/recipesite
    depends_on:
      - "database"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  database:
    image: "postgres:14"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=django_app_db
      - POSTGRES_USER=django_app_user
      - POSTGRES_PASSWORD=django_app_password
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
