services:
  nginx:
    build: ./nginx
    container_name: test_deploy_nginx
    volumes:
      - ./recipesite/static:/app/recipesite/static/
    ports:
      - 8008:80
    depends_on:
      - web
  web:
    environment:
      - HT_DEBUG=True
    command: poetry run python /app/recipesite/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres
    env_file: .postgres.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
