[tool.poetry]
name = "recipes.riceprower.com"
version = "0.1.0"
description = "A cooking and recipes website for the Rice-Prower family"
authors = ["Galen Rice <grice@protonmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.1"
django-admin-sortable2 = "^2.1"
django-environ = "^0.9.0"
django-filter = "^22.1"
django-fractions = "^2.0.0"
django-tinymce = "^3.4.0"
djangorestframework = "^3.13.1"
gunicorn = "^20.1.0"
markdown = "^3.4.1"
pillow = "^9.2.0"
psycopg2-binary = "^2.9.3"
secure = "^0.3.0"
uvicorn = {version = "^0.18.2", extras = ["standard"]}
wheel = "^0.37.1"
fontawesomefree = "^6.1.2"

[tool.poetry.dev-dependencies]
bandit = "^1.7.4"
black = "^22.6.0"
flake8 = "^5.0.4"
flake8-annotations = "^2.9.0"
flake8-docstrings = "^1.6.0"
pre-commit = "^2.20.0"
pytest = "^7.1.2"
pytest-django = "^4.5.2"

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-s -v"
pythonpath = "recipesite"
DJANGO_SETTINGS_MODULE = "core.settings"

[tool.bandit]
exclude_dirs = ["tests"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
