[tool.poetry]
name = "hometools"
version = "0.1.0"
description = "A collection of tools used in the Rice-Prower home on their server and stuff."
license = "MIT"
authors = ["Galen Rice <galen.rice@atumbomb.com>"]
readme = "README.md"
repository = "https://github.com/GriceTurrble/hometools"

[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.1.5"
django-environ = "^0.4.5"
django-fractions = "^2.0.0"
django-tinymce = "^3.2.0"
django-admin-sortable2 = "^0.7.8"
djangorestframework = "^3.12.2"
django-filter = "^2.4.0"
Markdown = "^3.3.3"
psycopg2 = "^2.8.6"
Pillow = "^8.1.0"
wheel = "^0.36.2"

[tool.poetry.dependencies.gunicorn]
version = "^20.0.4"
markers = "platform_system == 'Linux'"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
pytest-django = "^4.1.0"
flake8 = "^3.8.4"
black = "^20.8b1"
pre-commit = "^2.10.0"
fabric = "^2.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
