[tool.poetry]
name = "recipes.riceprower.com"
version = "0.1.0"
description = ""
authors = ["Galen Rice <grice@protonmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.0.2"
django-admin-sortable2 = "^1.0"
django-environ = "^0.8.1"
django-filter = "^21.1"
django-fractions = "^2.0.0"
django-tinymce = "^3.4.0"
djangorestframework = "^3.13.1"
gunicorn = "^20.1.0"
markdown = "^3.3.6"
pillow = "^9.0.1"
psycopg2-binary = "^2.9.3"
secure = "^0.3.0"
wheel = "^0.37.1"
uvicorn = "^0.17.5"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
pytest-django = "^4.5.2"
flake8 = "^3.9.0"
pre-commit = "^2.17.0"
black = "^22.1"
bandit = "^1.7.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
