# Generated by Django 3.1.2 on 2020-10-19 01:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
import djfractions.models.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_remove_recipe_ingredients"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeingredient",
            name="order",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Order in which this ingredient appears in the list of ingredients for a recipe.",
            ),
        ),
        migrations.AlterField(
            model_name="ingredienttype",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Name of this type of ingredient",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="time_to_cook",
            field=models.DurationField(
                blank=True,
                default=datetime.timedelta(0),
                help_text="Estimated time to cook this recipe (not including prep time).",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="time_to_prep",
            field=models.DurationField(
                blank=True,
                default=datetime.timedelta(0),
                help_text="Estimated time to prepare this recipe (not including cook time).",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="title",
            field=models.CharField(
                db_index=True,
                help_text="Title of this recipe. Give it a snappy name to remember it by! (must be unique!)",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount",
            field=djfractions.models.fields.DecimalFractionField(
                coerce_thirds=True,
                decimal_places=2,
                help_text="Amount of this ingredient per the 'amount unit-of-measure'. Accepts fractions.",
                limit_denominator=None,
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount_uom",
            field=models.CharField(
                help_text="Unit of measure for 'amount'.", max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="ingredient_type",
            field=models.ForeignKey(
                help_text="The type of this ingredient. Please avoid duplicates!",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="recipes.ingredienttype",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="recipe",
            field=models.ForeignKey(
                help_text="The Recipe this ingredient goes in.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients",
                to="recipes.recipe",
            ),
        ),
        migrations.CreateModel(
            name="RecipeDirection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "time_modified",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                ("content", tinymce.models.HTMLField()),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="directions",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
