# Generated by Django 3.1.2 on 2020-10-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_loads_of_updates"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="subtitle",
            field=models.CharField(
                blank=True,
                help_text="Short description for this recipe.",
                max_length=255,
            ),
        ),
    ]
