# Generated by Django 3.1.2 on 2020-10-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0009_auto_20201030_1117"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredienttype",
            name="plural_name",
            field=models.CharField(
                blank=True,
                help_text="Plural name of this type of ingredient",
                max_length=255,
            ),
        ),
    ]
