# Generated by Django 3.1.3 on 2020-11-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0011_recipe_nutrition_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount_uom",
            field=models.CharField(
                choices=[
                    ("blank", "(blank)"),
                    ("cup", "cup"),
                    ("dash", "dash"),
                    ("fluid-ounce", "fluid ounce"),
                    ("fuckton", "fuckton"),
                    ("gallon", "gallon"),
                    ("gram", "gram"),
                    ("kilogram", "kilogram"),
                    ("liter", "liter"),
                    ("ml", "ml"),
                    ("package", "package"),
                    ("packet", "packet"),
                    ("pinch", "pinch"),
                    ("pint", "pint"),
                    ("pound", "pound"),
                    ("quart", "quart"),
                    ("tbsp", "tablespoon"),
                    ("tsp", "teaspoon"),
                    ("weight-ounce", "ounce"),
                ],
                default="blank",
                help_text="Unit of measure for 'amount'.",
                max_length=20,
            ),
        ),
    ]
