# Generated by Django 3.1.6 on 2021-02-15 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0014_auto_20201224_2033"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredienttype",
            old_name="plural_name",
            new_name="_plural_name",
        ),
    ]
