# Generated by Django 3.0.4 on 2020-04-01 20:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import invoices.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "time_modified",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                ("line_1", models.CharField(max_length=255)),
                ("line_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("NJ", "New Jersey"),
                            ("AK", "Alaska"),
                            ("AL", "Alabama"),
                            ("AR", "Arkansas"),
                            ("AZ", "Arizona"),
                            ("CA", "California"),
                            ("CO", "Colorado"),
                            ("CT", "Connecticut"),
                            ("DC", "District of Columbia"),
                            ("DE", "Delaware"),
                            ("FL", "Florida"),
                            ("GA", "Georgia"),
                            ("HI", "Hawaii"),
                            ("IA", "Iowa"),
                            ("ID", "Idaho"),
                            ("IL", "Illinois"),
                            ("IN", "Indiana"),
                            ("KS", "Kansas"),
                            ("KY", "Kentucky"),
                            ("LA", "Louisiana"),
                            ("MA", "Massachusetts"),
                            ("MD", "Maryland"),
                            ("ME", "Maine"),
                            ("MI", "Michigan"),
                            ("MN", "Minnesota"),
                            ("MO", "Missouri"),
                            ("MS", "Mississippi"),
                            ("MT", "Montana"),
                            ("NB", "Nebraska"),
                            ("NC", "North Carolina"),
                            ("ND", "North Dakota"),
                            ("NE", "Nebraska"),
                            ("NH", "New Hampshire"),
                            ("NM", "New Mexico"),
                            ("NV", "Nevada"),
                            ("NY", "New York"),
                            ("OH", "Ohio"),
                            ("OK", "Oklahoma"),
                            ("OR", "Oregon"),
                            ("PA", "Pennsylvania"),
                            ("PR", "Puerto Rico"),
                            ("RI", "Rhode Island"),
                            ("SC", "South Carolina"),
                            ("SD", "South Dakota"),
                            ("TN", "Tennessee"),
                            ("TX", "Texas"),
                            ("UT", "Utah"),
                            ("VA", "Virginia"),
                            ("VT", "Vermont"),
                            ("WA", "Washington"),
                            ("WI", "Wisconsin"),
                            ("WV", "West Virginia"),
                            ("WY", "Wyoming"),
                            ("AA", "U.S. Armed Forces – Americas[d]"),
                            ("AE", "U.S. Armed Forces – Europe[e]"),
                            ("AP", "U.S. Armed Forces – Pacific[f]"),
                            ("AS", "American Samoa"),
                            ("CM", "Northern Mariana Islands"),
                            ("CZ", "Panama Canal Zone"),
                            ("FM", "Micronesia"),
                            ("GU", "Guam"),
                            ("MH", "Marshall Islands"),
                            ("MP", "Northern Mariana Islands"),
                            ("PI", "Philippine Islands"),
                            ("PW", "Palau"),
                            ("TT", "Trust Territory of the Pacific Islands"),
                            ("VI", "U.S. Virgin Islands"),
                        ],
                        default="NJ",
                        max_length=2,
                    ),
                ),
                ("country", models.CharField(default="US", max_length=5)),
                ("zip_code", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name_plural": "addresses",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "time_modified",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("phone", invoices.models.PhoneNumberField(blank=True, max_length=20)),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="invoices.Address",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "time_modified",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "hourly_rate",
                    invoices.models.CurrencyField(
                        decimal_places=2, max_digits=8, verbose_name="Rate per hour ($)"
                    ),
                ),
                (
                    "_project_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Project name"
                    ),
                ),
                (
                    "_client_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Client name"
                    ),
                ),
                (
                    "_client_address_line_1",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "_client_address_line_2",
                    models.CharField(blank=True, max_length=255),
                ),
                ("_client_address_city", models.CharField(blank=True, max_length=255)),
                (
                    "_client_address_state",
                    models.CharField(
                        choices=[
                            ("NJ", "New Jersey"),
                            ("AK", "Alaska"),
                            ("AL", "Alabama"),
                            ("AR", "Arkansas"),
                            ("AZ", "Arizona"),
                            ("CA", "California"),
                            ("CO", "Colorado"),
                            ("CT", "Connecticut"),
                            ("DC", "District of Columbia"),
                            ("DE", "Delaware"),
                            ("FL", "Florida"),
                            ("GA", "Georgia"),
                            ("HI", "Hawaii"),
                            ("IA", "Iowa"),
                            ("ID", "Idaho"),
                            ("IL", "Illinois"),
                            ("IN", "Indiana"),
                            ("KS", "Kansas"),
                            ("KY", "Kentucky"),
                            ("LA", "Louisiana"),
                            ("MA", "Massachusetts"),
                            ("MD", "Maryland"),
                            ("ME", "Maine"),
                            ("MI", "Michigan"),
                            ("MN", "Minnesota"),
                            ("MO", "Missouri"),
                            ("MS", "Mississippi"),
                            ("MT", "Montana"),
                            ("NB", "Nebraska"),
                            ("NC", "North Carolina"),
                            ("ND", "North Dakota"),
                            ("NE", "Nebraska"),
                            ("NH", "New Hampshire"),
                            ("NM", "New Mexico"),
                            ("NV", "Nevada"),
                            ("NY", "New York"),
                            ("OH", "Ohio"),
                            ("OK", "Oklahoma"),
                            ("OR", "Oregon"),
                            ("PA", "Pennsylvania"),
                            ("PR", "Puerto Rico"),
                            ("RI", "Rhode Island"),
                            ("SC", "South Carolina"),
                            ("SD", "South Dakota"),
                            ("TN", "Tennessee"),
                            ("TX", "Texas"),
                            ("UT", "Utah"),
                            ("VA", "Virginia"),
                            ("VT", "Vermont"),
                            ("WA", "Washington"),
                            ("WI", "Wisconsin"),
                            ("WV", "West Virginia"),
                            ("WY", "Wyoming"),
                            ("AA", "U.S. Armed Forces – Americas[d]"),
                            ("AE", "U.S. Armed Forces – Europe[e]"),
                            ("AP", "U.S. Armed Forces – Pacific[f]"),
                            ("AS", "American Samoa"),
                            ("CM", "Northern Mariana Islands"),
                            ("CZ", "Panama Canal Zone"),
                            ("FM", "Micronesia"),
                            ("GU", "Guam"),
                            ("MH", "Marshall Islands"),
                            ("MP", "Northern Mariana Islands"),
                            ("PI", "Philippine Islands"),
                            ("PW", "Palau"),
                            ("TT", "Trust Territory of the Pacific Islands"),
                            ("VI", "U.S. Virgin Islands"),
                        ],
                        default="NJ",
                        max_length=2,
                    ),
                ),
                (
                    "_client_address_country",
                    models.CharField(default="US", max_length=5),
                ),
                (
                    "_client_address_zip_code",
                    models.CharField(blank=True, max_length=10),
                ),
                (
                    "_client_phone",
                    invoices.models.PhoneNumberField(
                        blank=True, max_length=20, verbose_name="Client phone"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Invoice name",
                    ),
                ),
                ("invoice_date", models.DateField()),
                ("cycle_start_date", models.DateField(verbose_name="Invoiced from")),
                ("cycle_end_date", models.DateField(verbose_name="Invoiced to")),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_invoices",
                        to="invoices.Client",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "time_modified",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                ("_orig_item_id", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_items",
                        to="invoices.Invoice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "time_modified",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=50, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("DEV", "Development"),
                            ("SUPPORT", "Support"),
                            ("MAINT", "Maintenance"),
                            ("OTHER", "Other"),
                        ],
                        default="DEV",
                        max_length=7,
                    ),
                ),
                ("ticket_number", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "time_modified",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                ("phone", invoices.models.PhoneNumberField(blank=True, max_length=20)),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="invoices.Address",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "time_modified",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "billing_cycle",
                    models.PositiveIntegerField(
                        default=14, verbose_name="Billing cycle recurrence (in days)"
                    ),
                ),
                (
                    "first_cycle_end_date",
                    models.DateField(
                        verbose_name="Date of the end of the first billing cycle."
                    ),
                ),
                (
                    "hourly_rate",
                    invoices.models.CurrencyField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="Rate per hour in $",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="invoices.Client",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ItemLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "time_modified",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                ("_item_name", models.CharField(blank=True, max_length=255)),
                ("_item_description", models.CharField(blank=True, max_length=255)),
                ("date", models.DateField()),
                (
                    "hours",
                    invoices.models.HoursField(
                        decimal_places=1,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="invoices.Item",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_logs",
                        to="invoices.Project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="item",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="invoices.Project",
            ),
        ),
        migrations.CreateModel(
            name="InvoiceItemLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "time_modified",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                ("_orig_log_id", models.PositiveIntegerField()),
                ("date", models.DateField()),
                (
                    "hours",
                    invoices.models.HoursField(
                        decimal_places=1,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "invoice_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_item_logs",
                        to="invoices.InvoiceItem",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_invoices",
                to="invoices.Project",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_invoices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
