authors:
  griceturrble:
    name: Galen Rice
    description: Creator
    avatar: https://github.com/griceturrble.png
    url: https://github.com/griceturrble
  mollsprow:
    name: Molly Prower
    description: Creator
    avatar: https://github.com/mollsprow.png
    url: https://github.com/mollsprow
