# Docs:
# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
# https://github.com/docker/build-push-action/blob/master/docs/advanced/push-multi-registries.md
# https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-ghcrio
# https://github.com/docker/build-push-action/blob/master/docs/advanced/tags-labels.md


name: Docker build & publish
on:
  # Nightly builds (uses no-cache option for the build process; see below)
  schedule:
    - cron: '0 6 * * *'  # daily at 6am UTC (roughly 1am US/Eastern)

  # successful code quality checks on the main branch (from ci workflow)
  # (which runs on pushes and PRs)
  workflow_run:
    workflows: ["Code quality checks"]
    types: [completed]
    branches:
      - 'main'

env:
  REPO: ${{ github.repository }}

jobs:
  image_publish:
    name: Push Docker image to registries
    runs-on: "ubuntu-latest"
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Adapted from:
      # https://github.community/t/additional-function-s-lowercase-uppercase/140632/4
      - name: lowercase REPO for build-push
        run: |
          echo "REPO_LOWER=${REPO,,}" >> ${GITHUB_ENV}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ env.REPO_LOWER }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule,pattern=nightly
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=edge

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # - name: Build image
      #   run: docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          # push to registry
          push: ${{ github.event_name != 'pull_request' }}
          # attempt to pull new images every time
          pull: true
          # ignore the cache (to avoid insecure cached layers)
          no-cache: ${{ github.event_name == 'schedule' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
