name: Build and publish a Docker image to ghcr.io
on:
  # publish on releases, e.g. v2.1.13 (image tagged as "2.1.13" - "v" prefix is removed)
  # release:
  #   types: [ published ]

  # publish on pushes to the main branch (image tagged as "latest")
  workflow_dispatch:
  push:
    branches:
      - main

env:
  REPO: ${{ github.repository }}

jobs:
  image_publish:
    name: Push Docker image to registries
    runs-on: "ubuntu-latest"
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # - name: Build image
      #   run: docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: lowercase REPO for build-push
        run: |
          echo "REPO_LOWER=${REPO,,}" >> ${GITHUB_ENV}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags:
            # user/app:latest
            ghcr.io/${{ env.REPO_LOWER }}:latest
